/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2024-06-03 08:07:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1715843364991L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1717400420747L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1715843361433L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	if(request.getAttribute("result") != null){
		int result = (int)request.getAttribute("result");
		if(result > 0){ 
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write(" alert(\"저장되었습니다\")\n");
      out.write("</script>\r\n");
		} else{ 
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	 alert(\"저장실패\")\r\n");
      out.write("	</script>\r\n");
 }
	}
	int custo = (int) request.getAttribute("custo");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	const phoneReg = /^(0)\\d{1,2}-\\d{3,4}-\\d{4}$/;\r\n");
      out.write("	function validate(){\r\n");
      out.write("		if(form.custname.value===\"\"){\r\n");
      out.write("			alert(\"회원 성명 입력하지 않음\");\r\n");
      out.write("			form.custname.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(form.phone.value===\"\"){\r\n");
      out.write("			alert(\"전화번호 입력\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}else{\r\n");
      out.write("			console.log(phoneReg.test(form.phone.value));\r\n");
      out.write("			if(!phoneReg.test(form.phone.value)){\r\n");
      out.write("				alert(\"전화번호 형식\");\r\n");
      out.write("				form.phone.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(form.address.value===\"\"){\r\n");
      out.write("			alert(\"회원 주소 입력하지 않음\");\r\n");
      out.write("			form.address.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(form.joindate.value===\"\"){\r\n");
      out.write("			alert(\"회원 날짜 입력하지 않음\");\r\n");
      out.write("			form.address.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(form.grade.value===\"\"){\r\n");
      out.write("			alert(\"회원 등급 입력하지 않음\");\r\n");
      out.write("			form.address.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		} else{\r\n");
      out.write("			if(!(form.grade.value===\"A\"||form.grade.value===\"B\"||form.grade.value===\"C\")){\r\n");
      out.write("				alert(\"고객등급 확인\");\r\n");
      out.write("				form.grade.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		return true;\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("* {margin: 0; padding: 0; list-style:none; text-decoration: none;}\r\n");
      out.write("\r\n");
      out.write("html, body {width:100%; height:100%}\r\n");
      out.write("\r\n");
      out.write("header {width:100%; height: 100px; position:relative;\r\n");
      out.write("		background: #0000ff; color:#ffffff; \r\n");
      out.write("		text-align: center; line-height: 100px;}\r\n");
      out.write("\r\n");
      out.write("nav 	{width:100%; height: 50px; position:relative;\r\n");
      out.write("		background: lightgray; color:black; \r\n");
      out.write("		line-height: 50px;	}\r\n");
      out.write("		\r\n");
      out.write("nav ul {display: flex;}\r\n");
      out.write("\r\n");
      out.write("nav li {margin:0px 3.5%; line-height: 50px;}\r\n");
      out.write("			 \r\n");
      out.write("section { width: 100%; height: calc(100% - 200px); }\r\n");
      out.write("\r\n");
      out.write("footer {width:100%; height: 50px;\r\n");
      out.write("		background: #0000ff; color:#ffffff; \r\n");
      out.write("		text-align: center; line-height: 50px;}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<h1>쇼핑몰 회원관리 ver1.0</h1>\r\n");
      out.write("	</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("* {margin: 0; padding: 0; list-style:none; text-decoration: none;}\r\n");
      out.write("\r\n");
      out.write("html, body {width:100%; height:100%}\r\n");
      out.write("\r\n");
      out.write("header {width:100%; height: 100px; position:relative;\r\n");
      out.write("		background: #0000ff; color:#ffffff; \r\n");
      out.write("		text-align: center; line-height: 100px;}\r\n");
      out.write("\r\n");
      out.write("nav 	{width:100%; height: 50px; position:relative;\r\n");
      out.write("		background: lightgray; color:black; \r\n");
      out.write("		line-height: 50px;	}\r\n");
      out.write("		\r\n");
      out.write("nav ul {display: flex;}\r\n");
      out.write("\r\n");
      out.write("nav li {margin:0px 3.5%; line-height: 50px;}\r\n");
      out.write("			 \r\n");
      out.write("section { width: 100%; height: calc(100% - 200px); }\r\n");
      out.write("\r\n");
      out.write("footer {width:100%; height: 50px;\r\n");
      out.write("		background: #0000ff; color:#ffffff; \r\n");
      out.write("		text-align: center; line-height: 50px;}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"Register\">회원등록</a></li>\r\n");
      out.write("			<li><a href=\"GetMember\">회원목록조회</a></li>\r\n");
      out.write("			<li><a href=\"money.jsp\">회원매출조회</a></li>\r\n");
      out.write("			<li><a href=\"NewFile.jsp\">홈으로</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<h1>홈쇼핑 회원 등록</h1>\r\n");
      out.write("<form name=\"form\" action=\"RegisterCtrl\" method=\"post\" onsubmit=\"return validate()\">\r\n");
      out.write("<input type=\"hidden\" name = \"action\" value =\"register\">\r\n");
      out.write("	<table>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>회원번호(자동발생)</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"custo\" / value=\"");
      out.print(custo);
      out.write("\" disabled=\"disabled\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>회원성명</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"custname\" /></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>회원전화</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"phone\" /></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>회원주소</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"address\" /></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>가입일자</td>\r\n");
      out.write("			<td><input type=\"date\" name=\"joindate\" /></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>고객등급(A:VIP,B:일반,C:직원)</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"grade\" /></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>도시코드</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"city\" /></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td></td>\r\n");
      out.write("			<td><input type=\"submit\" value=\"등록\"/><input type=\"button\" value=\"조회\" onclick=\"location.href='getMember.jsp'\"/></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("* {margin: 0; padding: 0; list-style:none; text-decoration: none;}\r\n");
      out.write("\r\n");
      out.write("html, body {width:100%; height:100%}\r\n");
      out.write("\r\n");
      out.write("header {width:100%; height: 100px; position:relative;\r\n");
      out.write("		background: #0000ff; color:#ffffff; \r\n");
      out.write("		text-align: center; line-height: 100px;}\r\n");
      out.write("\r\n");
      out.write("nav 	{width:100%; height: 50px; position:relative;\r\n");
      out.write("		background: lightgray; color:black; \r\n");
      out.write("		line-height: 50px;	}\r\n");
      out.write("		\r\n");
      out.write("nav ul {display: flex;}\r\n");
      out.write("\r\n");
      out.write("nav li {margin:0px 3.5%; line-height: 50px;}\r\n");
      out.write("			 \r\n");
      out.write("section { width: 100%; height: calc(100% - 200px); }\r\n");
      out.write("\r\n");
      out.write("footer {width:100%; height: 50px;\r\n");
      out.write("		background: #0000ff; color:#ffffff; \r\n");
      out.write("		text-align: center; line-height: 50px;}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer>\r\n");
      out.write("	<p>HRDKorea copyright &copy; 2016 All right reserved. Human Resources Development Service of Korea</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
